export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const FB_STORE_WORDS = 'FB_STORE_WORDS';
export const FB_FETCH_WORDS = 'FB_FETCH_WORDS';
export const HARVEST_WORDS = 'HARVEST_WORDS';

export const BACKGROUND_PORT_SET = 'BACKGROUND_PORT_SET';
// export const BACKGROUND_PORT_INIT = 'BACKGROUND_PORT_INIT';
export const BACKGROUND_PORT_REMOVE = 'BACKGROUND_PORT_REMOVE';