export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const FB_FETCH_START = 'FB_FETCH_START';
export const FB_FETCH_SUCCESS = 'FB_FETCH_SUCCESS';
export const FB_FETCH_FAIL = 'FB_FETCH_FAIL';
// export const FB_FETCH_WORDS = 'FB_FETCH_WORDS';

export const FB_STORE_START = 'FB_STORE_START';
export const FB_STORE_SUCCESS = 'FB_STORE_SUCCESS';
export const FB_STORE_FAIL = 'FB_STORE_FAIL';
// export const FB_STORE_WORDS = 'FB_STORE_WORDS';

export const RIPS_FETCH_START = 'RIPS_FETCH_START';
export const RIPS_FETCH_SUCCESS = 'RIPS_FETCH_SUCCESS';
export const RIPS_FETCH_FAIL = 'RIPS_FETCH_FAIL';
export const RIPS_ADD_USER_DATA = 'RIPS_ADD_USER_DATA';
// export const RIPS_FETCH_WORDS = 'RIPS_FETCH_WORDS';

export const BACKGROUND_PORT_SET = 'BACKGROUND_PORT_SET';
export const BACKGROUND_PORT_REMOVE = 'BACKGROUND_PORT_REMOVE';
export const BACKGROUND_PORT_ERROR = 'BACKGROUND_PORT_ERROR';
export const PORT_INIT_COLLECT = 'PORT_INIT_COLLECT';
// export const BACKGROUND_PORT_INIT = 'BACKGROUND_PORT_INIT';